### ISSUE TITLE
i'm not having a mouse attached but the cursor still shows after adding the module

### ISSUE THREAD

**Issue by kibotu** [MarinescuEvghenii/MMM-Cursor#1]
did i miss something? o.o

**Comment by uxigene** [comment]
Hello @kibotu, hope I fix your Issue you can try to update it. Please be aware that the MigicMirror can't hide the cursor if window is not focused. You can check this discussion. https://forum.magicmirror.builders/topic/542/mouse-cursor-visible-on-reboot/5
